name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: get files
      uses: actions/checkout@v2
    - name: Setup Dotnet 3.1.101
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    - name: Build Project
      shell: bash
      run:
        dotnet build --configuration Release --output ./output
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: mccrina
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
